BlogCore/BlogCore/Areas/Admin/Controllers/ArticlesController.cs
using BlogCore.DataAccess.Data.Repository.IRepository;
using BlogCore.Models;
using BlogCore.Models.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace BlogCore.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class ArticlesController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly IWebHostEnvironment _webHostEnvironment;

        public ArticlesController(IUnitOfWork unitOfWork, IWebHostEnvironment webHostEnvironment)
        {
            _unitOfWork = unitOfWork;
            _webHostEnvironment = webHostEnvironment;
        }

        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult Create()
        {
            ArticleViewModel articleViewModel = new ArticleViewModel()
            {
                Article = new Article(),
                ListCategory = _unitOfWork.Category.GetListCategory()
            };

            return View(articleViewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(ArticleViewModel articleViewModel)
        {
            if (ModelState.IsValid)
            {
                string rootPath = _webHostEnvironment.WebRootPath;
                var files = HttpContext.Request.Form.Files;
                if (articleViewModel.Article.Id == 0 && files.Count() > 0 )
                {
                    string fileName = Guid.NewGuid().ToString();
                    var loaded = Path.Combine(rootPath, @"images\articles");
                    var extension = Path.GetExtension(files[0].FileName);


                    using (var fileStreams = new FileStream(Path.Combine(loaded, fileName + extension), FileMode.Create))
                    {
                        files[0].CopyTo(fileStreams);
                    }

                    articleViewModel.Article.UrlImage = @"\images\articles\" + fileName + extension;
                    articleViewModel.Article.CreatedDate = DateTime.Now.ToString();

                    _unitOfWork.Article.Add(articleViewModel.Article);
                    _unitOfWork.Save();

                    return RedirectToAction(nameof(Index));
                }
                else
                {
                    ModelState.AddModelError("Image", "Debes seleccionar una imagen");
                }
            }

            articleViewModel.ListCategory = _unitOfWork.Category.GetListCategory();
            return View(articleViewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(ArticleViewModel articleViewModel)
        {
            if (ModelState.IsValid)
            {
                string rootPath = _webHostEnvironment.WebRootPath;
                var files = HttpContext.Request.Form.Files;
                var articleFromDb = _unitOfWork.Article.Get(articleViewModel.Article.Id);


                if (files.Count() > 0)
                {
                    //New image for the article
                    string fileName = Guid.NewGuid().ToString();
                    var loaded = Path.Combine(rootPath, @"images\articles");
                    var extension = Path.GetExtension(files[0].FileName);
                    var newExtension = Path.GetExtension(files[0].FileName);

                    var pathImage = Path.Combine(rootPath, articleFromDb.UrlImage.TrimStart('\\'));

                    if (System.IO.File.Exists(pathImage))
                    {
                        System.IO.File.Delete(pathImage);
                    }

                    //Load file
                    using (var fileStreams = new FileStream(Path.Combine(loaded, fileName + extension), FileMode.Create))
                    {
                        files[0].CopyTo(fileStreams);
                    }

                    articleViewModel.Article.UrlImage = @"\images\articles\" + fileName + extension;
                    articleViewModel.Article.CreatedDate = DateTime.Now.ToString();

                    _unitOfWork.Article.Update(articleViewModel.Article);
                    _unitOfWork.Save();

                    return RedirectToAction(nameof(Index));
                }
                else
                {
                    articleViewModel.Article.UrlImage = articleFromDb.UrlImage;

                }

                _unitOfWork.Article.Update(articleViewModel.Article);
                _unitOfWork.Save();

                return RedirectToAction(nameof(Index));
            }

            articleViewModel.ListCategory = _unitOfWork.Category.GetListCategory();
            return View(articleViewModel);
        }

        [HttpGet]
        public IActionResult Edit(int? id)
        {
            ArticleViewModel articleViewModel = new ArticleViewModel()
            {
                Article = new Article(),
                ListCategory = _unitOfWork.Category.GetListCategory()
            };

            if(id != null)
            {
                articleViewModel.Article = _unitOfWork.Article.Get(id.GetValueOrDefault());
            }

            return View(articleViewModel);
        }



        #region Calls to API

        [HttpGet]
        public IActionResult GetAll()
        {
            return Json(new { data = _unitOfWork.Article.GetAll(includeProperties:"Category") });
        }

        [HttpDelete]
        public IActionResult Delete(int id)
        {
            var objFromDb = _unitOfWork.Article.Get(id);
            string rootPath = _webHostEnvironment.WebRootPath;
            var pathImage = Path.Combine(rootPath, objFromDb.UrlImage.TrimStart('\\'));

            if (System.IO.File.Exists(pathImage))
            {
                System.IO.File.Delete(pathImage);
            }

            if (objFromDb == null)
            {
                return Json(new { success = false, message = "Error borrando articulo" });
            }
            _unitOfWork.Article.Remove(objFromDb);
            _unitOfWork.Save();
            return Json(new { success = true, message = "Articulo borrado correctamente" });
        }


        #endregion

    }
}

BlogCore/BlogCore/Areas/Admin/Controllers/CategoriesController.cs
using BlogCore.DataAccess.Data.Repository.IRepository;
using BlogCore.Models;
using Microsoft.AspNetCore.Mvc;

namespace BlogCore.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class CategoriesController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public CategoriesController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult Create() 
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Category category)
        {
            if (ModelState.IsValid) 
            {
                _unitOfWork.Category.Add(category);
                _unitOfWork.Save();
                return RedirectToAction(nameof(Index));
            }

            return View(category);
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            Category category = new Category();
            category = _unitOfWork.Category.Get(id);
            if (category == null) 
            {
                return NotFound();
            }

            return View(category);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Category category)
        {
            if (ModelState.IsValid)
            {
                _unitOfWork.Category.Update(category);
                _unitOfWork.Save();
                return RedirectToAction(nameof(Index));
            }

            return View(category);
        }


        #region Calls to API

        [HttpGet]
        public IActionResult GetAll() 
        {
            return Json(new {data = _unitOfWork.Category.GetAll()});
        }

        [HttpDelete]
        public IActionResult Delete(int id) 
        {
            var objFromDb = _unitOfWork.Category.Get(id);
            if (objFromDb == null)
            {
                return Json(new {success = false, message = "Error borrando categoria"});
            }
            _unitOfWork.Category.Remove(objFromDb);
            _unitOfWork.Save();
            return Json(new { success = true, message = "Categoria borrada correctamente" });
        }
        
        #endregion

    }
}

BlogCore/BlogCore/Areas/Admin/Controllers/SlidersController.cs
using BlogCore.DataAccess.Data.Repository.IRepository;
using BlogCore.Models;
using BlogCore.Models.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace BlogCore.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class SlidersController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly IWebHostEnvironment _webHostEnvironment;

        public SlidersController(IUnitOfWork unitOfWork, IWebHostEnvironment webHostEnvironment)
        {
            _unitOfWork = unitOfWork;
            _webHostEnvironment = webHostEnvironment;
        }

        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Slider slider)
        {
            if (ModelState.IsValid)
            {
                string rootPath = _webHostEnvironment.WebRootPath;
                var files = HttpContext.Request.Form.Files;
                if (files.Count() > 0)
                {
                    string fileName = Guid.NewGuid().ToString();
                    var loaded = Path.Combine(rootPath, @"images\sliders");
                    var extension = Path.GetExtension(files[0].FileName);


                    using (var fileStreams = new FileStream(Path.Combine(loaded, fileName + extension), FileMode.Create))
                    {
                        files[0].CopyTo(fileStreams);
                    }

                    slider.UrlImage = @"\images\sliders\" + fileName + extension;

                    _unitOfWork.Slider.Add(slider);
                    _unitOfWork.Save();

                    return RedirectToAction(nameof(Index));
                }
                else
                {
                    ModelState.AddModelError("Image", "Debes seleccionar una imagen");
                }
            }
            return View(slider);
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            Slider slider = new Slider();
            slider = _unitOfWork.Slider.Get(id);
            if (slider == null)
            {
                return NotFound();
            }

            return View(slider);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Slider slider)
        {
            if (ModelState.IsValid)
            {
                string rootPath = _webHostEnvironment.WebRootPath;
                var files = HttpContext.Request.Form.Files;
                var sliderFromDb = _unitOfWork.Slider.Get(slider.Id);


                if (files.Count() > 0)
                {
                    //New image for the article
                    string fileName = Guid.NewGuid().ToString();
                    var loaded = Path.Combine(rootPath, @"images\sliders");
                    var extension = Path.GetExtension(files[0].FileName);
                    var newExtension = Path.GetExtension(files[0].FileName);

                    var pathImage = Path.Combine(rootPath, sliderFromDb.UrlImage.TrimStart('\\'));

                    if (System.IO.File.Exists(pathImage))
                    {
                        System.IO.File.Delete(pathImage);
                    }

                    //Load file
                    using (var fileStreams = new FileStream(Path.Combine(loaded, fileName + extension), FileMode.Create))
                    {
                        files[0].CopyTo(fileStreams);
                    }

                    slider.UrlImage = @"\images\sliders\" + fileName + extension;

                    _unitOfWork.Slider.Update(slider);
                    _unitOfWork.Save();

                    return RedirectToAction(nameof(Index));
                }
                else
                {
                    slider.UrlImage = sliderFromDb.UrlImage;

                }

                _unitOfWork.Slider.Update(slider);
                _unitOfWork.Save();

                return RedirectToAction(nameof(Index));
            }

            return View(slider);
        }


        #region Calls to API

        [HttpGet]
        public IActionResult GetAll()
        {
            return Json(new { data = _unitOfWork.Slider.GetAll() });
        }

        [HttpDelete]
        public IActionResult Delete(int id)
        {
            var objFromDb = _unitOfWork.Slider.Get(id);
            if (objFromDb == null)
            {
                return Json(new { success = false, message = "Error borrando slider" });
            }
            _unitOfWork.Slider.Remove(objFromDb);
            _unitOfWork.Save();
            return Json(new { success = true, message = "Slider borrado correctamente" });
        }

        #endregion

    }
}

BlogCore/BlogCore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BlogCore</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap5.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    @* <link rel="stylesheet" href="~/BlogCore.styles.css" asp-append-version="true" /> *@

    <!--Css todos-->
    <link rel="stylesheet" href="https://cdn.datatables.net/2.0.0/css/dataTables.dataTables.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.13.2/themes/base/jquery-ui.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/2.1.4/toastr.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/1.1.3/sweetalert.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" />

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg bg-body-tertiary">
            <div class="container-fluid">
                <a class="navbar-brand" href="#">BlogCore</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor04" aria-controls="navbarColor04" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarColor04">
                    <ul class="navbar-nav me-auto">
                        <li class="nav-item">
                            <a class="nav-link active" href="#">
                                Inicio
                                <span class="visually-hidden">(current)</span>
                            </a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Administrar Contenidos</a>
                            <div class="dropdown-menu">
                                <a class="dropdown-item" asp-area="Admin" asp-controller="Categories" asp-action="Index">Categorias</a>
                                <a class="dropdown-item" asp-area="Admin" asp-controller="Articles" asp-action="Index">Articulos</a>
                                <a class="dropdown-item" asp-area="Admin" asp-controller="Sliders" asp-action="Index">Sliders</a>
                                <a class="dropdown-item" asp-area="Admin" asp-controller="Users" asp-action="Index">Usuarios</a>
                            </div>
                        </li>
                    </ul>
                    <form class="d-flex">
                        <input class="form-control me-sm-2" type="search" placeholder="Buscar">
                        <button class="btn btn-secondary my-2 my-sm-0" type="submit">Buscar</button>
                    </form>
                </div>
                <partial name="_LoginPartial.cshtml" />
            </div>
        </nav>
        
        <!-- Partial View Slider-->
        @if(ViewBag.IsHome == true){
            <partial name="_Slider" />
        }
        

    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - BlogCore - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>

    <!--Js plugins-->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.13.2/jquery-ui.min.js"></script>
    <script src="https://cdn.datatables.net/2.0.0/js/dataTables.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery.serializeJSON/3.2.1/jquery.serializejson.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/2.1.4/toastr.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/1.1.3/sweetalert.min.js"></script>
    
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

BlogCore/BlogCore/Views/Shared/_Slider.cshtml
@model BlogCore.Models.ViewModels.HomeViewModel
<!--Slider-->

<div id="carouselSlider" class="carousel slide">
    <div class="carousel-inner">
        @{
            int count = 0;
            foreach (var slider in Model.Sliders)
            {
                var itemDynamic = count++ == 0 ? "active" : "";

                if(slider.State == true)
                {
                    <div class="carousel-item @itemDynamic">
                        <h1 class="text-white text-center bg-black py-1"> @Html.Raw(slider.Name)</h1>
                        <img src="@Url.Content(slider.UrlImage)" class="d-block w-100">
                    </div>
                }
            }
        }
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#carouselSlider" data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#carouselSlider" data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
    </button>
</div>

<!--End Slider-->

BlogCore/BlogCore/Views/Shared/_ViewCreateBack.cshtml
<div class="row" >
    <div class="col">
        <button type = "submit" class="btn btn-primary form-control"> Crear </button>
    </div>
    &nbsp;
    <div class="col">
        <a asp-action="Index" class="btn btn-success form-control"> Volver atras</a>
    </div>
</div>